[package]
name = "granite"
version = "0.1.0"
edition = "2021"

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
libc = "0.2"
bitflags = "1.0"
once_cell = "1.17"

[dependencies.cairo-rs]
git = "https://github.com/gtk-rs/gtk-rs-core"
version = "0.18"

[dependencies.glib]
git = "https://github.com/gtk-rs/gtk-rs-core"
version = "0.18"

[dependencies.gio]
git = "https://github.com/gtk-rs/gtk-rs-core"
version = "0.18"

[dependencies.gdk-pixbuf]
git = "https://github.com/gtk-rs/gtk-rs-core"
version = "0.18"

[dependencies.gdk]
package = "gdk4"
git = "https://github.com/gtk-rs/gtk4-rs"
version = "0.7"

[dependencies.gtk]
package = "gtk4"
git = "https://github.com/gtk-rs/gtk4-rs"
version = "0.7"

[dependencies.ffi]
package = "granite-sys"
path = "./sys"
