[package]
name = "granite-rs"
version = "0.1.0"
edition = "2021"
authors = ["David Hewitt <davidmhewitt@gmail.com>"]
readme = "../README.md"
description = "Rust bindings for Granite"
license = "MIT"
homepage = "https://github.com/davidmhewitt/granite-rs"
repository = "https://github.com/davidmhewitt/granite-rs"
categories = ["api-bindings", "gui"]
keywords = ["gtk4-rs", "GUI"]

[lib]
name = "granite"

[features]
dox = [
    "cairo-rs/dox",
    "glib/dox",
    "gio/dox",
    "gdk-pixbuf/dox",
    "gdk/dox",
    "gtk/dox",
    "ffi/dox",
]

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
libc = "0.2"
bitflags = "1.0"
once_cell = "1.17"

[dependencies.cairo-rs]
version = "0.17"

[dependencies.glib]
version = "0.17"

[dependencies.gio]
version = "0.17"

[dependencies.gdk-pixbuf]
version = "0.17"

[dependencies.gdk]
package = "gdk4"
version = "0.6"

[dependencies.gtk]
package = "gtk4"
version = "0.6"

[dependencies.ffi]
package = "granite-rs-sys"
path = "./sys"
version = "0.1.0"
