[package]
name = "granite-rs"
version = "1.0.0"
edition = "2021"
authors = ["David Hewitt <davidmhewitt@gmail.com>"]
readme = "../README.md"
description = "Rust bindings for Granite"
license = "MIT"
homepage = "https://github.com/davidmhewitt/granite-rs"
repository = "https://github.com/davidmhewitt/granite-rs"
categories = ["api-bindings", "gui"]
keywords = ["gtk4-rs", "GUI"]

[features]
v7_1 = ["ffi/v7_1"]
v7_2 = ["ffi/v7_2", "v7_1"]
v7_3 = ["ffi/v7_3", "v7_2"]

[package.metadata.docs.rs]
all-features = true
rustc-arg = ["--cfg", "docsrs"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
libc = "0.2"
bitflags = "2.2"
once_cell = "1.17"

[dependencies.glib]
version = "0.18"

[dependencies.gio]
version = "0.18"

[dependencies.gdk]
package = "gdk4"
version = "0.7"

[dependencies.gtk]
package = "gtk4"
version = "0.7"

[dependencies.ffi]
package = "granite-rs-sys"
path = "./sys"
version = "0.2.1"
