[options]
library = "Granite"
version = "7.0"
min_cfg_version = "7"
target_path = "."
girs_directories = ["../../gir-files/", "../.."]
work_mode = "sys"
single_version_file = true

external_libraries = [
    "Gdk",
    "Gio",
    "GLib",
    "GObject",
    "Gtk",
]
