[package]
name = "granite-rs-examples"
version = "0.1.0"
edition = "2021"

[dependencies.granite]
path = "../granite"

[dependencies.glib]
git = "https://github.com/gtk-rs/gtk-rs-core"

[dependencies.gio]
git = "https://github.com/gtk-rs/gtk-rs-core"
version = "0.18"

[dependencies.gtk]
package = "gtk4"
git = "https://github.com/gtk-rs/gtk4-rs"
