[package]
name = "granite-rs-examples"
version = "0.1.0"
edition = "2021"

[dependencies.granite]
package = "granite-rs"
path = "../granite"

[dependencies.glib]
version = "0.17"

[dependencies.gio]
version = "0.17"

[dependencies.gtk]
package = "gtk4"
version = "0.6"
