// This file was generated by gir (https://github.com/gtk-rs/gir)
// from 
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GraniteAccelLabel", sizeof(GraniteAccelLabel), alignof(GraniteAccelLabel));
    printf("%s;%zu;%zu\n", "GraniteAccelLabelClass", sizeof(GraniteAccelLabelClass), alignof(GraniteAccelLabelClass));
    printf("%s;%zu;%zu\n", "GraniteDatePicker", sizeof(GraniteDatePicker), alignof(GraniteDatePicker));
    printf("%s;%zu;%zu\n", "GraniteDatePickerClass", sizeof(GraniteDatePickerClass), alignof(GraniteDatePickerClass));
    printf("%s;%zu;%zu\n", "GraniteDialog", sizeof(GraniteDialog), alignof(GraniteDialog));
    printf("%s;%zu;%zu\n", "GraniteDialogClass", sizeof(GraniteDialogClass), alignof(GraniteDialogClass));
    printf("%s;%zu;%zu\n", "GraniteDrawingBufferSurface", sizeof(GraniteDrawingBufferSurface), alignof(GraniteDrawingBufferSurface));
    printf("%s;%zu;%zu\n", "GraniteDrawingBufferSurfaceClass", sizeof(GraniteDrawingBufferSurfaceClass), alignof(GraniteDrawingBufferSurfaceClass));
    printf("%s;%zu;%zu\n", "GraniteDrawingColor", sizeof(GraniteDrawingColor), alignof(GraniteDrawingColor));
    printf("%s;%zu;%zu\n", "GraniteDrawingColorClass", sizeof(GraniteDrawingColorClass), alignof(GraniteDrawingColorClass));
    printf("%s;%zu;%zu\n", "GraniteDrawingUtilities", sizeof(GraniteDrawingUtilities), alignof(GraniteDrawingUtilities));
    printf("%s;%zu;%zu\n", "GraniteDrawingUtilitiesClass", sizeof(GraniteDrawingUtilitiesClass), alignof(GraniteDrawingUtilitiesClass));
    printf("%s;%zu;%zu\n", "GraniteHeaderLabel", sizeof(GraniteHeaderLabel), alignof(GraniteHeaderLabel));
    printf("%s;%zu;%zu\n", "GraniteHeaderLabelClass", sizeof(GraniteHeaderLabelClass), alignof(GraniteHeaderLabelClass));
    printf("%s;%zu;%zu\n", "GraniteHyperTextView", sizeof(GraniteHyperTextView), alignof(GraniteHyperTextView));
    printf("%s;%zu;%zu\n", "GraniteHyperTextViewClass", sizeof(GraniteHyperTextViewClass), alignof(GraniteHyperTextViewClass));
    printf("%s;%zu;%zu\n", "GraniteMessageDialog", sizeof(GraniteMessageDialog), alignof(GraniteMessageDialog));
    printf("%s;%zu;%zu\n", "GraniteMessageDialogClass", sizeof(GraniteMessageDialogClass), alignof(GraniteMessageDialogClass));
    printf("%s;%zu;%zu\n", "GraniteModeSwitch", sizeof(GraniteModeSwitch), alignof(GraniteModeSwitch));
    printf("%s;%zu;%zu\n", "GraniteModeSwitchClass", sizeof(GraniteModeSwitchClass), alignof(GraniteModeSwitchClass));
    printf("%s;%zu;%zu\n", "GraniteOverlayBar", sizeof(GraniteOverlayBar), alignof(GraniteOverlayBar));
    printf("%s;%zu;%zu\n", "GraniteOverlayBarClass", sizeof(GraniteOverlayBarClass), alignof(GraniteOverlayBarClass));
    printf("%s;%zu;%zu\n", "GranitePlaceholder", sizeof(GranitePlaceholder), alignof(GranitePlaceholder));
    printf("%s;%zu;%zu\n", "GranitePlaceholderClass", sizeof(GranitePlaceholderClass), alignof(GranitePlaceholderClass));
    printf("%s;%zu;%zu\n", "GraniteServicesContractIface", sizeof(GraniteServicesContractIface), alignof(GraniteServicesContractIface));
    printf("%s;%zu;%zu\n", "GraniteServicesContractorError", sizeof(GraniteServicesContractorError), alignof(GraniteServicesContractorError));
    printf("%s;%zu;%zu\n", "GraniteServicesContractorProxy", sizeof(GraniteServicesContractorProxy), alignof(GraniteServicesContractorProxy));
    printf("%s;%zu;%zu\n", "GraniteServicesContractorProxyClass", sizeof(GraniteServicesContractorProxyClass), alignof(GraniteServicesContractorProxyClass));
    printf("%s;%zu;%zu\n", "GraniteServicesSettingsSerializableIface", sizeof(GraniteServicesSettingsSerializableIface), alignof(GraniteServicesSettingsSerializableIface));
    printf("%s;%zu;%zu\n", "GraniteServicesSystem", sizeof(GraniteServicesSystem), alignof(GraniteServicesSystem));
    printf("%s;%zu;%zu\n", "GraniteServicesSystemClass", sizeof(GraniteServicesSystemClass), alignof(GraniteServicesSystemClass));
    printf("%s;%zu;%zu\n", "GraniteSettings", sizeof(GraniteSettings), alignof(GraniteSettings));
    printf("%s;%zu;%zu\n", "GraniteSettingsClass", sizeof(GraniteSettingsClass), alignof(GraniteSettingsClass));
    printf("%s;%zu;%zu\n", "GraniteSettingsColorScheme", sizeof(GraniteSettingsColorScheme), alignof(GraniteSettingsColorScheme));
    printf("%s;%zu;%zu\n", "GraniteSettingsPage", sizeof(GraniteSettingsPage), alignof(GraniteSettingsPage));
    printf("%s;%zu;%zu\n", "GraniteSettingsPageClass", sizeof(GraniteSettingsPageClass), alignof(GraniteSettingsPageClass));
    printf("%s;%zu;%zu\n", "GraniteSettingsPageStatusType", sizeof(GraniteSettingsPageStatusType), alignof(GraniteSettingsPageStatusType));
    printf("%s;%zu;%zu\n", "GraniteSettingsSidebar", sizeof(GraniteSettingsSidebar), alignof(GraniteSettingsSidebar));
    printf("%s;%zu;%zu\n", "GraniteSettingsSidebarClass", sizeof(GraniteSettingsSidebarClass), alignof(GraniteSettingsSidebarClass));
    printf("%s;%zu;%zu\n", "GraniteSimpleSettingsPage", sizeof(GraniteSimpleSettingsPage), alignof(GraniteSimpleSettingsPage));
    printf("%s;%zu;%zu\n", "GraniteSimpleSettingsPageClass", sizeof(GraniteSimpleSettingsPageClass), alignof(GraniteSimpleSettingsPageClass));
    printf("%s;%zu;%zu\n", "GraniteSwitchModelButton", sizeof(GraniteSwitchModelButton), alignof(GraniteSwitchModelButton));
    printf("%s;%zu;%zu\n", "GraniteSwitchModelButtonClass", sizeof(GraniteSwitchModelButtonClass), alignof(GraniteSwitchModelButtonClass));
    printf("%s;%zu;%zu\n", "GraniteTimePicker", sizeof(GraniteTimePicker), alignof(GraniteTimePicker));
    printf("%s;%zu;%zu\n", "GraniteTimePickerClass", sizeof(GraniteTimePickerClass), alignof(GraniteTimePickerClass));
    printf("%s;%zu;%zu\n", "GraniteToast", sizeof(GraniteToast), alignof(GraniteToast));
    printf("%s;%zu;%zu\n", "GraniteToastClass", sizeof(GraniteToastClass), alignof(GraniteToastClass));
    printf("%s;%zu;%zu\n", "GraniteValidatedEntry", sizeof(GraniteValidatedEntry), alignof(GraniteValidatedEntry));
    printf("%s;%zu;%zu\n", "GraniteValidatedEntryClass", sizeof(GraniteValidatedEntryClass), alignof(GraniteValidatedEntryClass));
    return 0;
}
