name: Check Semver

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elementary/docker:unstable
    steps:
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y curl git jq
        git config --global --add safe.directory ${GITHUB_WORKSPACE}
    - uses: actions/checkout@v3
    - name: Check semver
      uses: obi1kenobi/cargo-semver-checks-action@main
      with:
        package: granite-rs, granite-rs-sys