name: Check Semver

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: fedora:rawhide
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: dnf install -y curl git gcc gcc-c++ make cmake libtool autoconf automake pkgconf-pkg-config glib2-devel gobject-introspection-devel gtk4-devel granite-7-devel
    - name: Check semver
      uses: obi1kenobi/cargo-semver-checks-action@main
      with:
        package: granite-rs, granite-rs-sys