name: Check Semver

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    container:
      image: elementary/docker:stable
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        apt-get update && apt-get install -y curl git jq
    - name: Check semver
      uses: obi1kenobi/cargo-semver-checks-action@v1
      with:
        crate-name: granite-rs