// This file was generated by gir (https://github.com/gtk-rs/gir)
// from
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

use glib::GStr;

#[doc(alias = "GRANITE_STYLE_CLASS_ACCENT")]
pub static STYLE_CLASS_ACCENT: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_ACCENT) };
#[doc(alias = "GRANITE_STYLE_CLASS_BACK_BUTTON")]
pub static STYLE_CLASS_BACK_BUTTON: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_BACK_BUTTON) };
#[doc(alias = "GRANITE_STYLE_CLASS_BADGE")]
pub static STYLE_CLASS_BADGE: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_BADGE) };
#[doc(alias = "GRANITE_STYLE_CLASS_CARD")]
pub static STYLE_CLASS_CARD: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_CARD) };
#[doc(alias = "GRANITE_STYLE_CLASS_CHECKERBOARD")]
pub static STYLE_CLASS_CHECKERBOARD: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_CHECKERBOARD) };
#[doc(alias = "GRANITE_STYLE_CLASS_CIRCULAR")]
pub static STYLE_CLASS_CIRCULAR: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_CIRCULAR) };
#[doc(alias = "GRANITE_STYLE_CLASS_COLOR_BUTTON")]
pub static STYLE_CLASS_COLOR_BUTTON: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_COLOR_BUTTON) };
#[doc(alias = "GRANITE_STYLE_CLASS_DEFAULT_DECORATION")]
pub static STYLE_CLASS_DEFAULT_DECORATION: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_DEFAULT_DECORATION) };
#[doc(alias = "GRANITE_STYLE_CLASS_DESTRUCTIVE_ACTION")]
pub static STYLE_CLASS_DESTRUCTIVE_ACTION: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_DESTRUCTIVE_ACTION) };
#[doc(alias = "GRANITE_STYLE_CLASS_DIALOG_CONTENT_AREA")]
pub static STYLE_CLASS_DIALOG_CONTENT_AREA: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_DIALOG_CONTENT_AREA) };
#[doc(alias = "GRANITE_STYLE_CLASS_H1_LABEL")]
pub static STYLE_CLASS_H1_LABEL: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_H1_LABEL) };
#[doc(alias = "GRANITE_STYLE_CLASS_H2_LABEL")]
pub static STYLE_CLASS_H2_LABEL: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_H2_LABEL) };
#[doc(alias = "GRANITE_STYLE_CLASS_H3_LABEL")]
pub static STYLE_CLASS_H3_LABEL: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_H3_LABEL) };
#[doc(alias = "GRANITE_STYLE_CLASS_H4_LABEL")]
pub static STYLE_CLASS_H4_LABEL: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_H4_LABEL) };
#[doc(alias = "GRANITE_STYLE_CLASS_KEYCAP")]
pub static STYLE_CLASS_KEYCAP: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_KEYCAP) };
#[doc(alias = "GRANITE_STYLE_CLASS_MODE_SWITCH")]
pub static STYLE_CLASS_MODE_SWITCH: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_MODE_SWITCH) };
#[doc(alias = "GRANITE_STYLE_CLASS_OSD")]
pub static STYLE_CLASS_OSD: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_OSD) };
#[doc(alias = "GRANITE_STYLE_CLASS_ROUNDED")]
pub static STYLE_CLASS_ROUNDED: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_ROUNDED) };
#[doc(alias = "GRANITE_STYLE_CLASS_SMALL_LABEL")]
pub static STYLE_CLASS_SMALL_LABEL: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_SMALL_LABEL) };
#[doc(alias = "GRANITE_STYLE_CLASS_TERMINAL")]
pub static STYLE_CLASS_TERMINAL: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_TERMINAL) };
#[doc(alias = "GRANITE_STYLE_CLASS_TITLE_LABEL")]
pub static STYLE_CLASS_TITLE_LABEL: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_TITLE_LABEL) };
#[doc(alias = "GRANITE_STYLE_CLASS_WARMTH")]
pub static STYLE_CLASS_WARMTH: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_WARMTH) };
#[doc(alias = "GRANITE_STYLE_CLASS_TEMPERATURE")]
pub static STYLE_CLASS_TEMPERATURE: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_TEMPERATURE) };
#[doc(alias = "GRANITE_STYLE_CLASS_LINKED")]
pub static STYLE_CLASS_LINKED: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_LINKED) };
#[doc(alias = "GRANITE_STYLE_CLASS_MENU")]
pub static STYLE_CLASS_MENU: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_MENU) };
#[doc(alias = "GRANITE_STYLE_CLASS_MENUITEM")]
pub static STYLE_CLASS_MENUITEM: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_MENUITEM) };
#[doc(alias = "GRANITE_STYLE_CLASS_DIM_LABEL")]
pub static STYLE_CLASS_DIM_LABEL: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_DIM_LABEL) };
#[doc(alias = "GRANITE_STYLE_CLASS_ERROR")]
pub static STYLE_CLASS_ERROR: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_ERROR) };
#[doc(alias = "GRANITE_STYLE_CLASS_FLAT")]
pub static STYLE_CLASS_FLAT: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_FLAT) };
#[doc(alias = "GRANITE_STYLE_CLASS_MESSAGE_DIALOG")]
pub static STYLE_CLASS_MESSAGE_DIALOG: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_MESSAGE_DIALOG) };
#[doc(alias = "GRANITE_STYLE_CLASS_SUGGESTED_ACTION")]
pub static STYLE_CLASS_SUGGESTED_ACTION: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_SUGGESTED_ACTION) };
#[doc(alias = "GRANITE_STYLE_CLASS_VIEW")]
pub static STYLE_CLASS_VIEW: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_VIEW) };
#[doc(alias = "GRANITE_STYLE_CLASS_WARNING")]
pub static STYLE_CLASS_WARNING: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_STYLE_CLASS_WARNING) };
#[doc(alias = "GRANITE_TOOLTIP_SECONDARY_TEXT_MARKUP")]
pub static TOOLTIP_SECONDARY_TEXT_MARKUP: &GStr =
    unsafe { GStr::from_utf8_with_nul_unchecked(ffi::GRANITE_TOOLTIP_SECONDARY_TEXT_MARKUP) };
